version: '3.9'

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=rdas-nev
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"
