version: '3.9'

services:
  db:
    container_name: db_service
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=rdas-nev
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"

  adminer-docker:
   container_name: adminer_service
   image: adminer:4.8.1
   restart: on-failure
   depends_on:
     - db
   ports:
     - "8080:8080"
